#############################################################################
# Makefile for building: bin/ptcan
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? 9? 22 09:37:04 2022
# Project:  ptcan.pro
# Template: app
# Command: /opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/qmake -spec /opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/linux-g++ CONFIG+=debug -o Makefile ptcan.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-poky-linux-gnueabi-gcc -march=armv7-a -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a9 --sysroot=/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi
CXX           = arm-poky-linux-gnueabi-g++ -march=armv7-a -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a9 --sysroot=/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi
DEFINES       = -DARM_PLATFORM -DQT_NO_DEBUG -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -O2 -pipe -g -feliminate-unused-debug-types -O2 -Wall -W -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -O2 -pipe -g -feliminate-unused-debug-types -std=c++0x -O2 -O2 -Wall -W -Wall -W -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/linux-g++ -I. -I/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qtopia/QtCore -I/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qtopia/QtNetwork -I/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qtopia/QtXml -I/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/include/qtopia -I. -Imutex -Iepoll -Itimer -Izprint -Icanbus -Icanpro -Itkcommon -Ireflect -Iprodata -Iprodata/sem -Iptxml -Imsg -Icandata -Imodbus -I1030app -Itk200 -Imoc_tmp
LINK          = arm-poky-linux-gnueabi-g++ -march=armv7-a -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a9 --sysroot=/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi
LFLAGS        = $(OE_QMAKE_LDFLAGS) -Wl,-rpath-link,/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib
LIBS          = $(SUBLIBS)  -L/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib -lQtXmlE -lQtNetworkE -lQtCoreE -lpthread 
AR            = arm-poky-linux-gnueabi-ar
RANLIB        = 
QMAKE         = /opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = $(OE_QMAKE_STRIP)
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = o_tmp/

####### Files

SOURCES       = main.cpp \
		timer/timers.cpp \
		canbus/can_bus.cpp \
		zprint/zprint.cpp \
		canpro/can_protocol.cpp \
		prodata/sem/syssem.cpp \
		msg/driver.cpp \
		msg/msg.cpp \
		msg/MsgMng.cpp \
		msg/MsgObject.cpp \
		candata/candata.cpp \
		1030app/1030pro.cpp \
		1030app/1030common.cpp \
		modbus/modbuscrc.cpp \
		candata/ptrwdatainfo.cpp \
		tk200/tk200pro.cpp \
		tk200/tk200cs.cpp \
		tkcommon/tkcommon.cpp \
		tkcommon/bsdev.cpp \
		zprint/netprint.cpp moc_tmp/moc_netprint.cpp
OBJECTS       = o_tmp/main.o \
		o_tmp/timers.o \
		o_tmp/can_bus.o \
		o_tmp/zprint.o \
		o_tmp/can_protocol.o \
		o_tmp/syssem.o \
		o_tmp/driver.o \
		o_tmp/msg.o \
		o_tmp/MsgMng.o \
		o_tmp/MsgObject.o \
		o_tmp/candata.o \
		o_tmp/1030pro.o \
		o_tmp/1030common.o \
		o_tmp/modbuscrc.o \
		o_tmp/ptrwdatainfo.o \
		o_tmp/tk200pro.o \
		o_tmp/tk200cs.o \
		o_tmp/tkcommon.o \
		o_tmp/bsdev.o \
		o_tmp/netprint.o \
		o_tmp/moc_netprint.o
DIST          = /opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/common/unix.conf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/common/linux.conf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base.conf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base-unix.conf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/common/g++-unix.conf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/qconfig.pri \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/modules/qt_webkit_version.pri \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/modules/qt_webkit_version.pri \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_functions.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_config.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/exclusive_builds.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_pre.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/release.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_post.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/shared.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/warn_on.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/unix/thread.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/moc.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/resources.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/uic.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/yacc.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/lex.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/include_source_dir.prf \
		ptcan.pro
QMAKE_TARGET  = ptcan
DESTDIR       = bin/
TARGET        = bin/ptcan

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ptcan.pro  /opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/linux-g++/qmake.conf /opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/common/unix.conf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/common/linux.conf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base.conf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base-unix.conf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/common/g++-unix.conf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/qconfig.pri \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/modules/qt_webkit_version.pri \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/modules/qt_webkit_version.pri \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_functions.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_config.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/exclusive_builds.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_pre.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/release.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_post.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/shared.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/warn_on.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/unix/thread.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/moc.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/resources.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/uic.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/yacc.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/lex.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/include_source_dir.prf \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/libQtXmlE.prl \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/libQtCoreE.prl \
		/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/libQtNetworkE.prl
	$(QMAKE) -spec /opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/linux-g++ CONFIG+=debug -o Makefile ptcan.pro
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/common/unix.conf:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/common/linux.conf:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base.conf:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base-unix.conf:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/common/g++-unix.conf:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/qconfig.pri:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/modules/qt_webkit_version.pri:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/modules/qt_webkit_version.pri:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_functions.prf:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_config.prf:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/exclusive_builds.prf:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_pre.prf:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/release.prf:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_post.prf:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/shared.prf:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/unix/gdb_dwarf_index.prf:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/warn_on.prf:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt.prf:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/unix/thread.prf:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/moc.prf:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/resources.prf:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/uic.prf:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/yacc.prf:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/lex.prf:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/features/include_source_dir.prf:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/libQtXmlE.prl:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/libQtCoreE.prl:
/opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/libQtNetworkE.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/poky/1.7/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/share/qtopia/mkspecs/linux-g++ CONFIG+=debug -o Makefile ptcan.pro

dist: 
	@$(CHK_DIR_EXISTS) o_tmp/ptcan1.0.0 || $(MKDIR) o_tmp/ptcan1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) o_tmp/ptcan1.0.0/ && $(COPY_FILE) --parents epoll/e_poll.h timer/timers.h canbus/can_bus.h canbus/can_relate.h zprint/version.h zprint/zprint.h canpro/can_protocol.h prodata/pro_data.h prodata/clist.h prodata/sem/syssem.h ptxml/ptxml.h reflect/reflect.h reflect/xmlprocess.h msg/define.h msg/driver.h msg/msg.h msg/MsgMng.h msg/MsgObject.h msg/msgtype.h candata/candata.h candata/candatainfo.h prodata/semshare.h prodata/sharemem.h prodata/ptdataapp.h 1030app/1030common.h 1030app/1030pro.h 1030app/run_mode.h modbus/modbuscrc.h prodata/zmap.h candata/ptrwdatainfo.h tk200/tk200pro.h tk200/tk200cs.h tkcommon/tkcommon.h mutex/mutex.h tkcommon/bsdev.h zprint/netprint.h o_tmp/ptcan1.0.0/ && $(COPY_FILE) --parents main.cpp timer/timers.cpp canbus/can_bus.cpp zprint/zprint.cpp canpro/can_protocol.cpp prodata/sem/syssem.cpp msg/driver.cpp msg/msg.cpp msg/MsgMng.cpp msg/MsgObject.cpp candata/candata.cpp 1030app/1030pro.cpp 1030app/1030common.cpp modbus/modbuscrc.cpp candata/ptrwdatainfo.cpp tk200/tk200pro.cpp tk200/tk200cs.cpp tkcommon/tkcommon.cpp tkcommon/bsdev.cpp zprint/netprint.cpp o_tmp/ptcan1.0.0/ && (cd `dirname o_tmp/ptcan1.0.0` && $(TAR) ptcan1.0.0.tar ptcan1.0.0 && $(COMPRESS) ptcan1.0.0.tar) && $(MOVE) `dirname o_tmp/ptcan1.0.0`/ptcan1.0.0.tar.gz . && $(DEL_FILE) -r o_tmp/ptcan1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_tmp/moc_netprint.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_tmp/moc_netprint.cpp
moc_tmp/moc_netprint.cpp: epoll/e_poll.h \
		zprint/netprint.h
	/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/moc4 $(DEFINES) $(INCPATH) zprint/netprint.h -o moc_tmp/moc_netprint.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

o_tmp/main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o o_tmp/main.o main.cpp

o_tmp/timers.o: timer/timers.cpp timer/timers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o o_tmp/timers.o timer/timers.cpp

o_tmp/can_bus.o: canbus/can_bus.cpp canbus/can_bus.h \
		canbus/can_relate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o o_tmp/can_bus.o canbus/can_bus.cpp

o_tmp/zprint.o: zprint/zprint.cpp zprint/zprint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o o_tmp/zprint.o zprint/zprint.cpp

o_tmp/can_protocol.o: canpro/can_protocol.cpp canpro/can_protocol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o o_tmp/can_protocol.o canpro/can_protocol.cpp

o_tmp/syssem.o: prodata/sem/syssem.cpp prodata/sem/syssem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o o_tmp/syssem.o prodata/sem/syssem.cpp

o_tmp/driver.o: msg/driver.cpp msg/driver.h \
		msg/msg.h \
		msg/MsgObject.h \
		msg/msgtype.h \
		msg/define.h \
		msg/MsgMng.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o o_tmp/driver.o msg/driver.cpp

o_tmp/msg.o: msg/msg.cpp msg/msg.h \
		msg/MsgObject.h \
		msg/msgtype.h \
		msg/define.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o o_tmp/msg.o msg/msg.cpp

o_tmp/MsgMng.o: msg/MsgMng.cpp msg/MsgMng.h \
		msg/msg.h \
		msg/MsgObject.h \
		msg/msgtype.h \
		msg/define.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o o_tmp/MsgMng.o msg/MsgMng.cpp

o_tmp/MsgObject.o: msg/MsgObject.cpp msg/MsgObject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o o_tmp/MsgObject.o msg/MsgObject.cpp

o_tmp/candata.o: candata/candata.cpp candata/candata.h \
		candata/candatainfo.h \
		candata/ptrwdatainfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o o_tmp/candata.o candata/candata.cpp

o_tmp/1030pro.o: 1030app/1030pro.cpp 1030app/1030pro.h \
		1030app/1030common.h \
		1030app/run_mode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o o_tmp/1030pro.o 1030app/1030pro.cpp

o_tmp/1030common.o: 1030app/1030common.cpp 1030app/1030common.h \
		1030app/run_mode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o o_tmp/1030common.o 1030app/1030common.cpp

o_tmp/modbuscrc.o: modbus/modbuscrc.cpp modbus/modbuscrc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o o_tmp/modbuscrc.o modbus/modbuscrc.cpp

o_tmp/ptrwdatainfo.o: candata/ptrwdatainfo.cpp candata/ptrwdatainfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o o_tmp/ptrwdatainfo.o candata/ptrwdatainfo.cpp

o_tmp/tk200pro.o: tk200/tk200pro.cpp tk200/tk200pro.h \
		tk200/tk200cs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o o_tmp/tk200pro.o tk200/tk200pro.cpp

o_tmp/tk200cs.o: tk200/tk200cs.cpp tk200/tk200cs.h \
		tk200/tk200pro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o o_tmp/tk200cs.o tk200/tk200cs.cpp

o_tmp/tkcommon.o: tkcommon/tkcommon.cpp tkcommon/tkcommon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o o_tmp/tkcommon.o tkcommon/tkcommon.cpp

o_tmp/bsdev.o: tkcommon/bsdev.cpp tkcommon/bsdev.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o o_tmp/bsdev.o tkcommon/bsdev.cpp

o_tmp/netprint.o: zprint/netprint.cpp zprint/netprint.h \
		epoll/e_poll.h \
		zprint/zprint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o o_tmp/netprint.o zprint/netprint.cpp

o_tmp/moc_netprint.o: moc_tmp/moc_netprint.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o o_tmp/moc_netprint.o moc_tmp/moc_netprint.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/work_zc/work/ || $(MKDIR) $(INSTALL_ROOT)/opt/work_zc/work/ 
	-$(INSTALL_PROGRAM) "bin/$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/work_zc/work/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/opt/work_zc/work/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/work_zc/work/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/work_zc/work/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

